### ISSUE TITLE
Submission of factR to Bioconductor

### ISSUE THREAD

**Issue by fursham-h** [Bioconductor/Contributions#1840]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/fursham-h/factR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by lshep** [comment]
Thank you for your submission. Please find my initial review below: 

**Build Report**

- [ ] Please try and correct NOTES

**General**

- [ ] We prefer the master branch be clean of other application files like   _pkgdown.yml and _codecov.yml. Please move these to a different  branch.

- [ ] For what its worth, I see lots of additional commits on your github that are not in the current Bioconductor git repository.  Please remember to sync the github with the version we would have and distribute to Bioconductor users by pushing to upstream.


**README**

- [ ] Include Bioconductor installation instructions


**DESCRIPTION**

- [ ] Please remove `LazyData: true` we have rarely found it useful and it can  slow installation. 


**ToDo**

- [ ] Remove or at least don't track in git.

**doc**

- [ ] Remove. All documentation should be generated automatically by the vignettes. 

**vignettes**

- [ ] include bioconductor instructions

- [ ] When downloading files and writing files in vignette to use as examples  please download to a temporary directory and/or downloading from places like gencode could display the use of caching so users don't have to repeatedly download files unless necessary (see BiocFileCache). Since I'm assuming the rda files you created and provide with your package are saved versions of these files, you might uses those in your runnable vignette code and show the downloads/create from scratch in an eval=F block.

- [ ] We generally don't allow downloading files from github. Why not additionally include in your package as extdata (not sure the size of the files if it is too large to do this -- you could also use annotationhub as well)?
  or use existing data already provided in Bioconductor from either other packages data/extdata  or AnnotationHub?
  


**data/R/man**

_General_

- [X] Well written code and I very much appreciate the organization and code level documentation. Coding in pipes can sometimes be challenging to determine what the code is doing, the internal code documentation alleviates this greatly!

- [X] I was unaware of the rlang outputs. Very interesting. I'm glad the traditional suppressMessage and suppressWarning still see to work with these implementations. 

- [ ] There are a few different files that contain commented out code blocks. Please remove any unneeded code blocks.  

_data.R_

- [ ] Can you expand on the documentation a bit and include source information. It seems like these are probably created from the files in the vignette and saved along the way? Providing the same information you did in the vignette in the man page would be good.

- [ ] You currently don't use the rda provided with the package anywhere? Why are these necessary then? If they are not used they should be removed.

- [ ] Expanded information like what are the 5 columns of object might also be helpful

_is\_gtf.R_

- [ ] I think the name of this is slightly misleading as its more like a validation function that the GRanges object has the valid column names needed from a gtf. Optional of course.

_predictDomains.R_

- [ ] You shouldn't need the initial paste in a stop as stop/warning/message automatically do a paste.  I'm curious as why you use rlang functions for most other places but the traditional stop here?

Please address the above issues.  When ready please trigger a new build and request a re-review commenting on how the above issues have been addressed or with commentary. 

Cheers

**Comment by fursham-h** [comment]
Hi @lshep, thank you very much for you comments! I will address the issues asap and trigger a new build

**Comment by fursham-h** [comment]
Hi @lshep, I've given your comment #3 under the vignette section some thought, and I was wondering if adding an accompanying ExperimentData would help solve the problem? These files are custom assembled GTFs and are at least 10MB in size after compression. Adding them to extdata within factR will violate the 5MB file size restriction. These files are necessary to demonstrate the functionality of factR in annotating custom transcripts.

What do you think?

**Comment by lshep** [comment]
Then including them in experimenthub to download for examples would be appropriate.  Please see [Creating a ExperimentHub package](http://bioconductor.org/packages/release/bioc/vignettes/ExperimentHubData/inst/doc/CreateAnExperimentHubPackage.html).  Summary: You could create an entirely separate package for this purpose or use this package by creating the needed metadata file and uploading to S3.    

I am still curious at there you use any of the data currently provided in  `data/`  if these objects are not being used, which I currently do not see where they are used?,  they should not be in the package.

**Comment by fursham-h** [comment]
Okay, those objects in `data/` was meant for examples and tests objects but I will remove them and use examples created by the vignette.

Also, is this [documentation](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#submitting-related-packages) the same as submitting an experimenthub data?

**Comment by lshep** [comment]
If you use the data objects its find to keep them.  I didn't see them being used but maybe I didn't look close enough? 

If you are creating an entirely separate package to store the data then you would use that referenced documentation to submit it here for review.  If you wanted to use the software package you currently created, you would simply upload the data and add the metadata file to it here and update the vignette accordingly to reference those files.  

Cheers

**Comment by fursham-h** [comment]
AdditionalPackage: https://github.com/fursham-h/factRdata

**Comment by fursham-h** [comment]
Hi @lshep, I have triggered a new built and addressed your comments below

> **Build Report**
> 
>     * [x]  Please try and correct NOTES
I have corrected to correct as much as I can  


> 
> 
> **General**
> 
>     * [x]  We prefer the master branch be clean of other application files like   _pkgdown.yml and _codecov.yml. Please move these to a different  branch.
These files have been removed from master branch


> 
>     * [x]  For what its worth, I see lots of additional commits on your github that are not in the current Bioconductor git repository.  Please remember to sync the github with the version we would have and distribute to Bioconductor users by pushing to upstream.
My apologies, the master branch is now sync with the Bioconductor git repository


> 
> 
> **README**
> 
>     * [x]  Include Bioconductor installation instructions
Added, thanks


> 
> 
> **DESCRIPTION**
> 
>     * [x]  Please remove `LazyData: true` we have rarely found it useful and it can  slow installation.
Removed, and amended `man` and `R/data.R` usage using `data()`


> 
> 
> **ToDo**
> 
>     * [x]  Remove or at least don't track in git.
Removed, thanks


> 
> 
> **doc**
> 
>     * [x]  Remove. All documentation should be generated automatically by the vignettes.
Removed, I finally understood how vignettes are generated on github and bioconductor


> 
> 
> **vignettes**
> 
>     * [x]  include bioconductor instructions
Included


> 
>     * [ ]  When downloading files and writing files in vignette to use as examples  please download to a temporary directory and/or downloading from places like gencode could display the use of caching so users don't have to repeatedly download files unless necessary (see BiocFileCache). Since I'm assuming the rda files you created and provide with your package are saved versions of these files, you might uses those in your runnable vignette code and show the downloads/create from scratch in an eval=F block.
I have assigned temporary files for input using `tempfile()`, and create a temp output directory using `tempdir()`.


> 
>     * [ ]  We generally don't allow downloading files from github. Why not additionally include in your package as extdata (not sure the size of the files if it is too large to do this -- you could also use annotationhub as well)?
>       or use existing data already provided in Bioconductor from either other packages data/extdata  or AnnotationHub?
I have created an additional package *factRdata* to store these data and I have commented its link above. The compressed GTF files are at least 10MB, do let me know if this is going to be a problem



> 
> 
> **data/R/man**
> 
> _General_
> 
>     * [x]  Well written code and I very much appreciate the organization and code level documentation. Coding in pipes can sometimes be challenging to determine what the code is doing, the internal code documentation alleviates this greatly!
> 
>     * [x]  I was unaware of the rlang outputs. Very interesting. I'm glad the traditional suppressMessage and suppressWarning still see to work with these implementations.
Thank you for these comments!


> 
>     * [x]  There are a few different files that contain commented out code blocks. Please remove any unneeded code blocks.
Removed



> 
> 
> _data.R_
> 
>     * [x]  Can you expand on the documentation a bit and include source information. It seems like these are probably created from the files in the vignette and saved along the way? Providing the same information you did in the vignette in the man page would be good.
I have included a more detailed description of these objects



> 
>     * [x]  You currently don't use the rda provided with the package anywhere? Why are these necessary then? If they are not used they should be removed.
As previously discussed, these rda files were used for testings and examples  


> 
>     * [x]  Expanded information like what are the 5 columns of object might also be helpful
Additional information added, thanks!


> 
> 
> _is_gtf.R_
> 
>     * [x]  I think the name of this is slightly misleading as its more like a validation function that the GRanges object has the valid column names needed from a gtf. Optional of course.
I agree, this is more of an internal function. I have unexported this function and removed the man pages.


> 
> 
> _predictDomains.R_
> 
>     * [x]  You shouldn't need the initial paste in a stop as stop/warning/message automatically do a paste.  I'm curious as why you use rlang functions for most other places but the traditional stop here?
I have substitute stop with rlang::abort. I guess I forgot to change this at some point haha

**Comment by fursham-h** [comment]
Ummmmm, @lshep I'm not sure if I am doing this right. I triggered a new *factR* built and then added the data package *factRdata*. I got an error on *factR* and addressed it, but a new built wasn't triggered because the *factRdata* package is under review.

**Comment by lshep** [comment]
It doesn't look like factRdata has been approved yet for building.  I will follow up today with the person that approves these.

**Comment by fursham-h** [comment]
Ahhh, no worries. Just to make sure that I'm doing things right. Thanks!

**Comment by mtmorgan** [comment]
I'm confused a bit; the data in factRdata are larger than package guidelines indicate (10-11MB, vs. max of 5 MB); were you meaning to make an ExperimentHub data package & resource?

**Comment by fursham-h** [comment]
Hi @mtmorgan, my intentions were to use factRdata as an experiment data package to contain the sample GTF files as extdata to demonstrate importing using factR. These custom transcriptomes are information-rich and occupy 10Mb even after compression, but I've read somewhere that files in an experiment data package may be larger than 5Mb (do correct me if I'm mistaken). ExperimentHub, as I understand it, holds R/Bioconductor objects and will not fit my purpose.

**Comment by lshep** [comment]
ExperimentHub can hold objects or raw files.  While the original intention for the hubs was to store processed objects, more recently we have recommended storing raw files and transforming with R code in the package.  We have advised against traditional experiment data packages and encouraged all packages to move towards experimentHub type packages.

**Comment by lshep** [comment]
Please convert factRdata to be an ExperimentHub package

**Comment by fursham-h** [comment]
Hi @lshep, yes I will do that asap

**Comment by lshep** [comment]
Do you plan on moving forward with the submission?  We normally expect movement within 2-3 weeks to keep the submission process moving forward.

**Comment by fursham-h** [comment]
Dear @lshep , my apologies I was caught up with work and haven't gotten around to uploading the data to S3. I guess it is best if I close this issue and resubmit another one when we're ready.

**Comment by lshep** [comment]
@fursham-h  Okay. No problem  When you are ready you can always request this original issue be reopened.  Cheers

**Comment by fursham-h** [comment]
Hi @lshep,

Hope you are well! I wish to re-open this issue and submit my package to Bioconductor. I have simplified the package and it now does not require additional ExperimentHub data.

**Comment by lshep** [comment]
@fursham-h thank you. I will have a look at the package in the next few weeks. To be clear - You no longer are submitting factRdata? only factR?

**Comment by fursham-h** [comment]
Yes @lshep, just factR.

**Comment by lshep** [comment]
I'm sorry for the delayed response I was away on holiday. I will get to this in the next few days.

**Comment by fursham-h** [comment]
No worries @lshep! Looking forward to your comments.

**Comment by lshep** [comment]
Sorry for the delay.  Please see comments below: 


**README**

OK

**DESCRIPTION**

OK

**NAMESPACE**

OK

**NEWS**

- [ ] Please don't have empty news section or change to subsections. `factR
  (development)` is empty section currently.

```
# factR (development)

# factR 0.99.4

```

**inst**

- [ ] Please include an `inst/scripts/` directory that describes how the data in
  `inst/extadata` was generated and any relevant source/references. It can be
  code, sudo-code or text. If the data was simluated in any way please state as
  such.


**vignette**

- [ ] Update to Bioconductor installation instructions.

- [ ] The "Constructing CDS information" link in 2.2.3 does not seem to be
  working.

- [ ] The citation is not appearing in your vignette. 

- [X] Very nicely written


**R code/build report**

- [x] Just a note of caution about using suppressWarnings/suppressMessage as
  doing such may hide real issues with code or messages that users could find
  useful. If appropriate maybe consider a verbose option to give users the
  option of the extra output.

**Comment by fursham-h** [comment]
Thank you for your comments @lshep! I will work on the changes. A question, can I include bash scripts in the inst/scripts folder?

**Comment by lshep** [comment]
I don't see why not.

**Comment by fursham-h** [comment]
Hi @lshep, I have made a new push to address the following comments:

> **NEWS**
> 
>     * [* ]  Please don't have empty news section or change to subsections. `factR (development)` is empty section currently.
Subsection removed

> **inst**
> 
>     * [ ]  Please include an `inst/scripts/` directory that describes how the data in
>       `inst/extadata` was generated and any relevant source/references. It can be
>       code, sudo-code or text. If the data was simluated in any way please state as
>       such.
Scripts added to `inst/scripts/`

> **vignette**
> 
>     * [x]  Update to Bioconductor installation instructions.
Added

>     * [x]  The "Constructing CDS information" link in 2.2.3 does not seem to be
>       working.
Link corrected

>     * [x ]  The citation is not appearing in your vignette.
I've knitted the vignette multiple times and I could see the citations. To address this, I've changed the Rmd output to `rmarkdown::html_document`. Do let me know if this is still a problem

>     * [x]  Very nicely written
👍🏽 

> **R code/build report**
> 
>     * [x]  Just a note of caution about using suppressWarnings/suppressMessage as
>       doing such may hide real issues with code or messages that users could find
>       useful. If appropriate maybe consider a verbose option to give users the
>       option of the extra output.
I have removed as much as I could, and will add verbose options in the near future.

**Comment by fursham-h** [comment]
Hi @lshep, do you have any comments or updates on this?

**Comment by lshep** [comment]
I will re-review in the next week. Sorry for the delay.

**Comment by fursham-h** [comment]
Thank you @lshep. Looking forward to your comments

**Comment by lshep** [comment]
Changes look good. thank you!

**Comment by fursham-h** [comment]
Thank you so much @lshep for your help! Should I close this issue now?

**Comment by lshep** [comment]
No. Please leave the issue open.  We will process all the accepted packages sometime this week and they will be added to the daily builders (http://bioconductor.org/checkResults/).  It will auto close the issue once its processed

**Comment by fursham-h** [comment]
Great, thanks!

**Comment by lshep** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/fursham-h.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("factR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/factR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
