### ISSUE TITLE
bugphyzz

### ISSUE THREAD

**Issue by sdgamboa** [Bioconductor/Contributions#3367]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/waldronlab/bugphyzz

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment]
We don't allow data to be store in github.  Please store data on zenodo or some other trusted server. If a trusted serve is not available please consider using ExperimentHub.

**Comment by sdgamboa** [comment]
@lshep, we have published our data on [zenodo](https://zenodo.org/records/10980813) and use it as the default option in our [main function](https://github.com/waldronlab/bugphyzz/blob/7e3d6a7af247ed3594e394d0d43755d8811083db/R/bugphyzz.R#L56-L58).

A couple of functions still use data from external sites. [One of them](https://github.com/waldronlab/bugphyzz/blob/devel/R/bacdive.R) is not exported. The [other](https://github.com/waldronlab/bugphyzz/blob/7e3d6a7af247ed3594e394d0d43755d8811083db/R/physiologies.R#L4-L7) is exported, but we wrote in the documentation that it should be used by curator/developers. These functions are not used in any other function meant for end users.

Finally, a dataset that was originally imported from a github repo is now included in the 
inst/extadata directory with a [description](https://github.com/waldronlab/bugphyzz/blob/devel/inst/scripts/README.md#validation_summarytsv) in inst/scripts.

Please let me know if I need to make more changes.

Thank you!

**Comment by lshep** [comment]
Please also include a section in the vignette that is similar to an abstract describing why you are submitting the package to bioconductor and a comparison to an existing Bioconductor packages.

**Comment by lshep** [comment]
We have added the package to git.bioconductor.org but I am having trouble kicking off an initial build of the package. I'm currently investigating.

**Comment by lshep** [comment]
For Now this should be true: 


Your package has been added to git.bioconductor.org to continue the 
pre-review process.  A build report will be posted shortly. Please
fix any ERROR and WARNING in the build report before a reviewer is
assigned or provide a justification on why you feel the ERROR or 
WARNING should be granted an exception.

IMPORTANT: Please read [this documentation][1] for setting
up remotes to push to git.bioconductor.org. All changes should be
pushed to git.bioconductor.org moving forward. It is required to push a
version bump to git.bioconductor.org to trigger a new build report.

Bioconductor utilized your github ssh-keys for git.bioconductor.org
access. To manage keys and future access you may want to active your
[Bioconductor Git Credentials Account][3]

[1]: http://contributions.bioconductor.org/git-version-control.html#new-package-workflow
[2]: https://github.com/Bioconductor/Contributions#what-to-expect
[3]: https://git.bioconductor.org/BiocCredentials

**Comment by lshep** [comment]
Figured out the issue.  If you have difficulty triggering builds with pushes to git.bioconductor.org let me know and I can try to reprocess the package but I think it should be okay.

**Comment by sdgamboa** [comment]
@lshep, I added an abstract to the vignette and expanded the introduction to describe the package in more detail. I explain how the package should fit within Bioconductor workflows and related packages. Please let me know if that fulfills the request.

I got an error in the build, but I think this is a problem with one of the dependencies of another package (mia): 

```
===============================

 R CMD BUILD

===============================

* checking for file bugphyzz/DESCRIPTION ... OK
* preparing bugphyzz:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building bugphyzz.Rmd using rmarkdown

Quitting from lines 291-294 [unnamed-chunk-9] (bugphyzz.Rmd)
Error: processing vignette 'bugphyzz.Rmd' failed with diagnostics:
package or namespace load failed for 'mia' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called 'scuttle'
--- failed re-building bugphyzz.Rmd

SUMMARY: processing the following file failed:
  bugphyzz.Rmd

Error: Vignette re-building failed.
Execution halted
```

**Comment by DarioS** [comment]
bugphyzz is a package that stores annotations regarding microbiomes and enables enrichment analysis to be done. It will be a useful addition for Bioconductor microbiome researchers. However, there are some modifications required for it to conform to the Bioconductor Developer's Guide.

- Inconsistent use of camelCase and snake_case coding. For example, `makeSignatures`, `importBugphyzz`, `force_download`, `exclude_rarely`. Please refer to [Function Names](https://contributions.bioconductor.org/r-code.html?#rcode-function-names) and [Variable Names](https://contributions.bioconductor.org/r-code.html?#variable-names) of the Bioconductor Developer's Guide and amend accordingly.

- Uses unnecessary `for` loops. For example,

```r
  output <- vector("list", length(files))
  for (i in seq_along(output)) {
    output[[i]] <- utils::read.csv(files[i], header = TRUE, skip = 1) |>
    dplyr::mutate(Attribute = tolower(.data$Attribute))
  }
  return(output)
```

  Please refer for [Vectorize](https://contributions.bioconductor.org/r-code.html#vectorize) and change all such instances to `vapply` or `lapply`.

- Package seems incomplete.

```
## Function for importing fatty acid compositions
## TODO This dataset needs more curation.
## TODO Names of the Fatty Acids should be more "user-friendly"
## TODO Maybe a threshold should be decided to consider a FA as present or not.
```

and

```
## TODO correct plant pathogenicity name earlier in the workflow or
## better yet, directly in the curation
```

  See [Comments](https://contributions.bioconductor.org/r-code.html?q=Todo#rcode-comments) section.
  
  > Commenting TODO’s should be avoided in published package code
  
  Please add the missing functionality descibed in TODO sections.

- Lack of input parameter checking. For example, `@param tax_id_type A character string. Valid options: NCBI_ID, Taxon_name.` However, the function specification has `tax_id_type = "NCBI_ID"` but it should instead be `tax_id_type = c("NCBI_ID", "Taxon_name")` and inside the function should be `tax_id_type <- match.arg(tax_id_type)`. See [R at Work](https://www.r-at-work.com/functions/base/match-arg.html) for an introductory tutorial about parameter checking in R.

- Package has good interoperability with existing Bioconductor infrastructure but could be better. For example, it relies on `data.frame` but it does not handle `DataFrame` foundational class from [S4Vectors](https://bioconductor.org/packages/release/bioc/html/S4Vectors.html).

```r
> bp[["aerophilicity"]] <- as(bp[["aerophilicity"]], "DataFrame")
> makeSignatures(dat = bp[["aerophilicity"]], tax_id_type = "Taxon_name", tax_level = "genus")
Error in UseMethod("filter") : 
  no applicable method for 'filter' applied to an object of class "c('DFrame', 'DataFrame', 'SimpleList', 'RectangularData', 'List', 'DataFrame_OR_NULL', 'Vector', 'list_OR_List', 'Annotated', 'vector_OR_Vector')"
```

- Vignette is not discoverable from the command line.
```r
> browseVignettes("bugphyzz")
No vignettes found by browseVignettes("bugphyzz")
```

- Vignette uses limma's voom approach for linear modelling. Justify why you use count modelling for non-count data.

```r
limma::voom(counts = assay(se), design = design, plot = FALSE)$E
> assay(se)[1:5, 1:5] # Not count data.
               700103497 700106940 700097304 700099015 700097644
Streptococcus   17.18097  18.50818  16.03412  15.40698 17.148602
Neisseria       16.82849  16.12832  15.12273  15.20496 13.653478
Porphyromonas   12.80149  12.73703  16.37312  15.05930  4.935801
Capnocytophaga  16.79096  15.31840  16.58074  17.05846 17.598692
Actinomyces     17.66332  17.65465  11.65284  16.26541 13.892903
```

> `counts`: A numeric `matrix` containing raw counts, or an `ExpressionSet` containing raw counts, or a `DGEList` object. Counts must be non-negative and `NA`s are not permitted.

**Comment by lshep** [comment]
@sdgamboa  may we expected updates soon?

**Comment by sdgamboa** [comment]
@lshep, yes. Thanks for following up. I've already made the required changes. I'll bump the version today.

**Comment by sdgamboa** [comment]
@lshep, I think there could be some issues with the connection on nebbiolo2 (Ubuntu). I keep getting an error when building the vignette or running the tests of the package. The error seems to be related to the function that downloads the data. This doesn't happen on my local machine (I deleted the cache). It doesn't happen on [GitHub](https://github.com/waldronlab/bugphyzz/actions/runs/10408899405/job/28827292689) either.

**Comment by sdgamboa** [comment]
Dear @DarioS,

Thank you for your feedback. I think I've addressed all of the requested changes below:

>+ Inconsistent use of camelCase and snake_case coding. For example, makeSignatures, importBugphyzz, force_download, exclude_rarely. Please refer to Function Names and Variable Names of the Bioconductor Developer's Guide and amend accordingly.

I homogenized all function names, variables, and arguments to camelCase. Please see
[issue#244](https://github.com/waldronlab/bugphyzz/issues/244).

>+ Uses unnecessary for loops.

I changed all `for loops` to `lapply` when a vector was being created. However, 
I left some `for loops` that were used for printing messages or modifying existing
vectors. Please see [issue#245](https://github.com/waldronlab/bugphyzz/issues/245).

>+ Lack of input parameter checking.

Added `match.args`. Please see [issue#246](https://github.com/waldronlab/bugphyzz/issues/246)

>+ Package seems incomplete...Please add the missing functionality described in TODO sections.

+ The annotations could always be expanded or changed in the future through versioning on Zenodo. So I converted the TODO regarding the fatty acids annotations into an issue. Decision about inclusion or not of this data will be taken at another time. Please see [issue#242](https://github.com/waldronlab/bugphyzz/issues/242).

+ Removed code from the `importBugphyzz` function. Curation changes were made directly in the source file. Please see [issues#247](https://github.com/waldronlab/bugphyzz/issues/247). A new version of the data was created on Zenodo.


>+ Package has good interoperability with existing Bioconductor infrastructure but could be better. For example, it relies on data.frame but it does not handle DataFrame foundational class from S4Vectors.

The makeSignatures function can now handle `S4Vectors::DataFrame` objects. Please see [issue#243](https://github.com/waldronlab/bugphyzz/issues/243).

>+ Vignette is not discoverable from the command line.

I was not able to reproduce this issue. I'm able to open the vignettes in my browser (Linux machine) with either `browseVignettes("bugphyzz")` or `vigentte("bugphyzz", "bugphyzz")`. I can do this in the linux terminal and the Rstudio console. I was able to do this after installing the package locally with:

```
R CMD build <bugphyzz-directory>
R CMD INSTALL <generatered-tar.gz>
```

>+ Vignette uses limma's voom approach for linear modeling. Justify why you use count modeling for non-count data.

The input for `limma::voom` was count data. Please note that the "assay" slot in the SummarizedExperiment changes from counts to normalized counts (output of limma) in the code. This procedure was done following the recommendation of the GSEA method. Please see [issue#248](https://github.com/waldronlab/bugphyzz/issues/248). I wrote all of this more explicitly in the main vignette.

Please let me know if other changes are required. Thanks.

**Comment by DarioS** [comment]
The issues raised have been addressed.

**Comment by lshep** [comment]
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/sdgamboa.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("bugphyzz")`. The package 'landing page' will be created at

https://bioconductor.org/packages/bugphyzz

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
