### ISSUE TITLE
FlowSorted.Blood.EPIC

### ISSUE THREAD

**Issue by lucassalas** [Bioconductor/Contributions#710]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/immunomethylomics/FlowSorted.Blood.EPIC

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Hey there -  You might get a screwy build report - you happen to push changes right when I was pushing some changes to the SinglePackageBuilders -  I'm monitoring and once the (buggy) report is done - I will rerun to get a more accurate - 
Sorry about that -

**Comment by lshep** [comment]
another report will be generated shortly

**Comment by lucassalas** [comment]
Hi Marcel,
I solved the error with the versions and the package was build in Linux and OS.
However, it seems that the Windows build is not working the report says:
PackageFileSize: -1.00 KiB in the tokay  compared to PackageFileSize: 479366.83 KiB in merida 2 or PackageFileSize: 366058.68 KiB in malbec.
This is a lfs storage. Could this be a problem on your end?
I found that something similar occurred a couple months ago with another package using this system.

Please let me know and thank you.

Lucas

**Comment by LiNk-NY** [comment]
Hi Lucas, @lucassalas 

Thanks for your submission. These different sizes may be due to OS-specific calculations although
the tokay2 number is invalid. Don't worry about it for now. 

The error on tokay2 stems from using the older `save` function in your version of R. 
I suggest your resave the datasets using R devel `3.5.0`. 
We would prefer that the package depends on `R (>= 3.5.0)` because it will be deployed with
this version of R (if it gets accepted before the deadline). 

Regards,
Marcel

**Comment by lshep** [comment]
sorry - my fault - rerunning now

**Comment by lucassalas** [comment]
Hi @lshep  and @LiNk-NY ,
Well, I resaved the rda with the alpha 3.5.0 version and the problem with tokay2 persists.

I believe the tokay2 problem is related to the git clone from the lfs system.
It still reports -1.0 KiB  instead of the actual size of the package. I checked other build reports and, it seems that this problem is not isolated but it is happening for several tokay2 builds for other contributors.

@lshep Thanks for rerunning the build.

Lucas

**Comment by lshep** [comment]
I actaully have it running one more time - the ERROR in that last report was an unrelated issue that should be corrected now  -  you should have a new report shortly

**Comment by LiNk-NY** [comment]
Hi Lucas, @lucassalas 

Please resave the dataset(s) in version 3 and make sure that you are using the argument explicitly
as the default in R `3.5` is to save in version 2. 

```
save(..., version = 3)
```

See https://cran.r-project.org/bin/windows/base/NEWS.R-3.5.0beta.html for details.

Regards,
Marcel

**Comment by lucassalas** [comment]
Hi @LiNk-NY ,
I resaved and compressed the rda files using 3.5.0 alpha to version 3. However, the error in tokay2 persists.

PackageFile: --
PackageFileSize: -1.00 KiB
BuildID:: FlowSorted.Blood.EPIC_20180413022657
PreProcessing: Accessing git_info. Starting Git clone. Installing dependencies. Installing package: FlowSorted.Blood.EPIC. Starting Build package.
PostProcessing: Accessing git_info complete. Finished Git clone. Installing dependency status: 0. Installing package status: 1. Build Package status: 1.

The the system did not generate the expected zip file and the process was stopped. Very strange.

Thanks,

Lucas

**Comment by LiNk-NY** [comment]
Hi Lucas, @lucassalas 

It seems like it is trying to run `load` on a zip file but I'm not sure why. 
I will have another team member have a look at it. 

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Lucas, @lucassalas 

Martin @mtmorgan noticed that you are using git LFS. 
Currently our build system does not support LFS. Please convert the repository to a 
regular git repository if possible or consider using `ExperimentHub` to distribute the data
in your package. 

See: [`ExperimentHub` vignette](http://www.bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html)

Best regards,
Marcel

**Comment by lucassalas** [comment]
Hi @lshep  and @LiNk-NY,

I am sorry, but I will require some additional help here. I am not sure how can I test locally my files and I believe the build report is wrong (all the files are now of size -1.0.) even after updatng the Namespace.

Let me try to summarize what I have done so far:
**These steps I believe are OK:**
1. I have uploaded the FlowSorted.Blood.EPIC.rda to ExperimentHub yesterday using aws.
2. I have made a make-data.R and make-metadata.R, I generated a metadata.csv and I tested locally using readMetadataFromCsv("D:/GitHub/FlowSorted.Blood.EPIC") and all the results were OK.
3. I deleted my git lfs files and the .gitatrributes I checked git lfs ls-files and it is empty. All the small rda files are now on git ls-files.

**Here the problems**
4. I tried to run  to devtools::document() and I got an error as the ExperimentHub snapshotDate is 2017-10-30
5. The object FlowSorted.Blood.EPIC cannot be onloaded using the zzz.R as it is not present on ExperimentHub

Maybe I am missing something, should I submit my metadata first @lshep ?

I am scratching my head with this, not sure how to proceed on my end.

Thanks for your help.

Lucas

**Comment by lshep** [comment]
I'm sorry I should have been more clear in the email - after you uploaded your data I still need to add it to the location and into ExperimentHub -  that was a temporary location - I will do that now

**Comment by lshep** [comment]
The data is now on experimentHub in the devel version of Bioconductor 3.7
```
> hub = ExperimentHub()
updating metadata: retrieving 1 resource
  |======================================================================| 100%
snapshotDate(): 2018-04-20
> query(hub, "FlowSorted")
ExperimentHub with 1 record
# snapshotDate(): 2018-04-20 
# names(): EH1136
# package(): FlowSorted.Blood.EPIC
# $dataprovider: GEO
# $species: Homo sapiens
# $rdataclass: RGChannelSet
# $rdatadateadded: 2018-04-20
# $title: FlowSorted.Blood.EPIC: Illumina Human Methylation data from EPIC o...
# $description: The FlowSorted.Blood.EPIC package contains Illumina HumanMet...
# $taxonomyid: 9606
# $genome: hg19
# $sourcetype: tar.gz
# $sourceurl: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE110554
# $sourcesize: NA
# $tags: c("ExperimentData", "Homo_sapiens_Data", "Tissue",
#   "MicroarrayData", "Genome", "TissueMicroarrayData",
#   "MethylationArrayData") 
# retrieve record with 'object[["EH1136"]]' 
```

Side note:  The `FlowSorted.Blood.EPIC.Rproj `  should not be git tracked -  please use `git rm`  - if you would like to keep this type of file in the future it should be added to the .gitignore file.

**Comment by lucassalas** [comment]
Hi Marcel @LiNk-NY and Lori @lshep ,

The package is finally Ok in all the systems.

The main dataset is hosted on ExperimentHub. I preferred to keep the package light and avoid onload calls as it was generating some issues. The code has been checked and the examples are working. I did a hard checking of all the code to try to avoid potential issues for the users. The only potential problem is that it will not be back compatible with minfi function and it will only work with ours for now, but I cannot do anything else with the current settings.

Please let me know what are the next steps or whether I should do any further adjustments for approval.

Best,

Lucas

**Comment by lshep** [comment]
The abnormal label should have been automatically removed - I'll investigate on our end why it wasn't but in the meantime have manually removed it -  sorry about that.

**Comment by lucassalas** [comment]
Hi Marcel @LiNk-NY,

Sorry for being pushy, but I just want to check if everything is Ok and the package can be accepted, or if we have to wait until October for the package to be released.

If the package is part of this release that would be very helpful for us though, so if you need further adjustments I a do them before the 29th internal deadline. Being the package part of the upcoming publication of the method and it will lead to a very quick implementation by multiple users in the field that have already shown interest in using it.

Thanks again for your help.

Best,

Lucas

**Comment by LiNk-NY** [comment]
Hi Lucas, @lucassalas 

Everything looks good. 
I will mark your package as accepted. Thank you for submitting to Bioconductor!

Best regards,
Marcel

**Comment by mtmorgan** [comment]
Sorry I will try and process this and other packages in time for tonight's build.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lucassalas.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"FlowSorted.Blood.EPIC\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/FlowSorted.Blood.EPIC

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by LiNk-NY** [comment]
Thanks Martin! @mtmorgan 

Lucas, @lucassalas, I will coordinate with our team here to add your package to the release manifest.
